MUSICA_MENU = "musica_menu.mp3"
SOM_COMECO_JOGO = "som_começo_jogo.wav"
MUSICA_JOGO = "musica_jogo.mp3"
SOM_ACERTO = "som_acerto.wav"
SOM_ERRO = "som_erro.wav"
MUSICA_FASE_FINALIZADA = "musica_fase_finalizada.wav"
MUSICA_FINAL = "musica_final.wav"